apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myfirstapp
  name: myfirstapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myfirstapp
    spec:
      containers:
      - image: runapp:latest
        name: runapp
        imagePullPolicy: Never
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myfirstapp
  name: myfirstapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myfirstapp
  type: LoadBalancer
status:
  loadBalancer: {}
