{{- if .Values.blue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "runapp.fullname" . }}
  labels:
    {{- include "runapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "runapp.selectorLabels" . | nindent 4 }}
{{- end -}}
